language: c
sudo: false
matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=3.5
    - os: linux
      env: PYTHON_VERSION=3.6
    - os: linux
      env: PYTHON_VERSION=3.7
    - os: osx
      env: PYTHON_VERSION=3.5
    - os: osx
      env: PYTHON_VERSION=3.6
    - os: osx
      env: PYTHON_VERSION=3.7

before_install:
  - export NPY_DISTUTILS_APPEND_FLAGS=1
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  - conda config --add channels conda-forge
  - conda create -q -n testenv
      python=$PYTHON_VERSION obspy "gfortran_${TRAVIS_OS_NAME}-64" "numpy>=1.15"
      pytest-cov
      sphinx sphinx_rtd_theme
  - conda activate testenv
  - conda list
install:
  - pip install -v --no-deps .
script:
  - mkdir empty; cd empty
  - pytest -v --cov=telewavesim --pyargs telewavesim
  - cd ../docs
  - make html
  - cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    email: false
deploy:
  provider: pages:git
  deploy_key: <deploy_key>
  edge: true # opt in to dpl v2
  local_dir: docs
